version: '3.1'
services:
  adminDb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=greetingAdmin
  adminer: #web client for postgres
    image: adminer
    restart: always
    depends_on:
      - adminDb
    ports:
      - 8085:8085