version: '3.1'
services:
  authDb:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=authUser
  adminer: #web client for postgres
    image: adminer
    restart: always
    depends_on:
      - authDb
    ports:
      - 8087:8087